function [template]=database_variabletemplates(ind)
  
  dbtemplatelist{1}=struct(                 ...
                'name',         '',         ...
                'label',        '',         ...
                'unit',         '',     	...
                'sitename',     '',         ...
                'group',        '',         ...
                'dscp',         '', 		...
                'filereader',   '',         ...
                'ndim',         [],         ...
                'val',          [],         ...
                'err',          [],         ...
                'tl',           [], 		...                
                'drawopt',      []          ...                
                );
              
  dbtemplatelist{2}=struct(                 ...
                'name',         '',         ...
                'label',        '',         ...
                'unit',         '',     	...
                'sitename',     '',         ...
                'group',        '',         ...
                'dscp',         '', 		...
                'filereader',   '',         ...
                'dim',          [],         ...
                'val',          [],         ...
                'err',          [],         ...
                'lat',          [],         ...
                'lon',          [],         ...
                'tl',           [], 		...                
                'drawopt',      []          ...                
                );                   
  template=dbtemplatelist{ind};
end