global database datasetinfo

% NOTE: Add the parameter information whenever a new parameters is added!

databasetemplate1=database_variabletemplates(1);
databasetemplate2=database_variabletemplates(2);

%% EISCAT level 0 data
parainfo={'ne_lv0',            ...
          'Ti_lv0',       ...
          'Te_lv0',            ...
          'vi_lv0'};
ix=ismember(parainfo,datasetinfo.paralist);
if ~isempty(parainfo(ix))
  % linked file for reading EISCAT data
  filereader='assign_EISCAT_lv0.m';
  
  %% Item 1: Electron density
  itemname='ne_lv0';
  database.(itemname)=databasetemplate2;
  item={                            ...
    'name',         itemname;        ...
    'label',        'n_e';    ...
    'unit',         'm^{-3}';          ...
    'ndim',          2;              ... 
    'group',        'EISCAT Level 0';    ...
    'dscp',         'Electron density';      ...
    'filereader',   filereader      ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  
  %% Item 2: Ion temperature
  itemname='Ti_lv0';
  database.(itemname)=databasetemplate2;
  item={                            ...
    'name',         itemname;        ...
    'label',        'T_i';    ...
    'unit',         'K';          ...
    'ndim',          2;              ... 
    'group',        'EISCAT Level 0';    ...
    'dscp',         'Ion temperature';      ...
    'filereader',   filereader      ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  
  %% Item 3: Electron temperature
  itemname='Te_lv0';
  database.(itemname)=databasetemplate2;
  item={                            ...
    'name',         itemname;        ...
    'label',        'T_e';    ...
    'unit',         'K';          ...
    'ndim',          2;              ... 
    'group',        'EISCAT Level 0';    ...
    'dscp',         'Electron temperature';      ...
    'filereader',   filereader      ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  
  %% Item 4: Line-of-sight velocity
  itemname='vi_lv0';
  database.(itemname)=databasetemplate2;
  item={                            ...
    'name',         itemname;        ...
    'label',        'v_i^{LoS}';    ...
    'unit',         'm/s';          ...
    'ndim',          2;              ... 
    'group',        'EISCAT Level 0';    ...
    'dscp',         'Line-of-sight velocity';      ...
    'filereader',   filereader      ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  
  %% Initialize plot settings
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  vis_init_EISCAT_lv0;
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end