global database datasetinfo

% NOTE: Add the parameter information whenever a new parameters is added!


databasetemplate=database_variabletemplates(2);

%% for EISpecGLOW
parainfo={'tau_ni', ...
          'nu_ni',         ...
          };
ix=ismember(parainfo,datasetinfo.paralist);
if ~isempty(parainfo(ix))
  % linked file for reading FPI data
  filereader='assign_EISCAT_cdt.m';
  

  
  %% Item 1: nu_ni
  itemname='nu_ni';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         itemname;        ...
    'label',        '\nu_{ni}';    ...
    'unit',         's^{-1}';          ...
    'ndim',          2;              ... 
    'group',        'collision frequency';    ...
    'dscp',         'neutral-ion collision frequency';      ...
    'filereader',   filereader      ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end  
  
    %% Item 1: nu_ni
  itemname='tau_ni';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         itemname;        ...
    'label',        '\tau_{ni}';    ...
    'unit',         's';          ...
    'ndim',          2;              ... 
    'group',        'collision frequency';    ...
    'dscp',         'E-folding time';      ...
    'filereader',   filereader      ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end 
  
  %% Initialize plot settings
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  vis_init_EISCAT_cdt;
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end