global database datasetinfo

drawopttemplate1=vis_drawopttemplates(1);
drawopttemplate2=vis_drawopttemplates(2);
% NOTE: Add the parameter information whenever a new parameters is added!

parainfo={'nu_ni', ...
          'tau_ni',       ...
          };
        
cmap=axes_colormaps(0);       

%% Item 1: emission profile
itemname='nu_ni';
database.(itemname).drawopt=drawopttemplate2;
item={                                  ...
      'plottype',       2;            ...
      'xdatagrid',      'off';          ...
      'xdatagridres',   [];             ...
      'xlabel',         'UT';       	...
      'ydatagrid',      'off';          ...
      'ydatagridres',   [];             ...
      'ydataname',      'alt';          ...
      'ylim',           [80 300];        ...
      'yscale',         'linear';       ...
      'ylabel',         'h';          ...
      'yunit',          [];             ...
      'zlim',           [1e-5 3e-3];    ...
      'zscale',         'log';       ...
      'colormap',       cmap{1}};
      
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end


%% Item 2: emission profile
itemname='tau_ni';
database.(itemname).drawopt=drawopttemplate2;
item={                                  ...
      'plottype',       2;            ...
      'xdatagrid',      'off';          ...
      'xdatagridres',   [];             ...
      'xlabel',         'UT';       	...
      'ydatagrid',      'off';          ...
      'ydatagridres',   [];             ...
      'ydataname',      'alt';          ...
      'ylim',           [80 290];        ...
      'yscale',         'linear';       ...
      'ylabel',         'h';          ...
      'yunit',          [];             ...
      'zlim',           [0.5 30];    ...
      'zscale',         'linear';       ...
      'colormap',       cmap{1}};
      
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end
