global database datasetinfo

drawopttemplate1=vis_drawopttemplates(1);
drawopttemplate2=vis_drawopttemplates(2);
% NOTE: Add the parameter information whenever a new parameters is added!

parainfo={'keolat'};
        
cmap=axes_colormaps(0);       
%% Item 1: keogram latitude
itemname='keolat';
database.(itemname).drawopt=drawopttemplate2;
item={                                  ...
      'plottype',       2.0;            ...
      'xdatagrid',      'off';          ...
      'xdatagridres',   [];             ...
      'xlabel',         'UT';       	...
      'ydataname',      'lat';          ...
      'ydatagrid',      'off';          ...
      'ydatagridres',   [];             ...
      'ylim',           [66.5 72];        ...
      'yscale',         'linear';       ...
      'ylabel',         'lat';          ...
      'yunit',          [];             ...
      'zlim',           [0 100];    ...
      'zscale',         'linear';       ...
      'colormap',       cmap{1}};
      
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end
