function [ output_args ] = vis_init_EISCAT_lv0( input_args )
%VIS_INIT_EISCAT_LV0 Summary of this function goes here
%   Detailed explanation goes here

global database datasetinfo

drawopttemplate1=vis_drawopttemplates(1);
drawopttemplate2=vis_drawopttemplates(2);
% NOTE: Add the parameter information whenever a new parameters is added!

%% EISCAT level 0 data
parainfo={'ne_lv0',            ...
          'Ti_lv0',       ...
          'Te_lv0',            ...
          'vi_lv0'};
        
cmap=axes_colormaps(1);
%% Item 1: electron density
itemname='ne_lv0';
database.(itemname).drawopt=drawopttemplate2;
item={                                  ...
      'plottype',       2;            ...
      'xdatagrid',      'off';          ...
      'xdatagridres',   [];             ...
      'xlabel',         'UT';       	...
      'ydatagrid',      'off';          ...
      'ydatagridres',   [];             ...
      'ydataname',      'alt';          ...
      'ylim',           [80 450];        ...
      'yscale',         'linear';       ...
      'ylabel',         'h';          ...
      'yunit',          'km';             ...
      'zlim',           [9e9 8e11];    ...
      'zscale',         'log';       ...
      'colormap',       cmap{1}};
      
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end


%% Item 2: Ion temperature
itemname='Ti_lv0';
database.(itemname).drawopt=drawopttemplate2;
item={                                  ...
      'plottype',       2;            ...
      'xdatagrid',      'off';          ...
      'xdatagridres',   [];             ...
      'xlabel',         'UT';       	...
      'ydatagrid',      'off';          ...
      'ydatagridres',   [];             ...
      'ydataname',      'alt';          ...
      'ylim',           [80 450];        ...
      'yscale',         'linear';       ...
      'ylabel',         'h';          ...
      'yunit',          'km';             ...
      'zlim',           [100 2500];    ...
      'zscale',         'linear';       ...
      'colormap',       cmap{1}};
      
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 3: Electron temperature
itemname='Te_lv0';
database.(itemname).drawopt=drawopttemplate2;
item={                                  ...
      'plottype',       2;            ...
      'xdatagrid',      'off';          ...
      'xdatagridres',   [];             ...
      'xlabel',         'UT';       	...
      'ydatagrid',      'off';          ...
      'ydatagridres',   [];             ...
      'ydataname',      'alt';          ...
      'ylim',           [80 450];        ...
      'yscale',         'linear';       ...
      'ylabel',         'h';          ...
      'yunit',          'km';             ...
      'zlim',           [500 3000];    ...
      'zscale',         'linear';       ...
      'colormap',       cmap{1}};
      
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 4: line of sight velocity
itemname='vi_lv0';
database.(itemname).drawopt=drawopttemplate2;
item={                                  ...
      'plottype',       2;            ...
      'xdatagrid',      'off';          ...
      'xdatagridres',   [];             ...
      'xlabel',         'UT';       	...
      'ydatagrid',      'off';          ...
      'ydatagridres',   [];             ...
      'ydataname',      'alt';          ...
      'ylim',           [80 450];        ...
      'yscale',         'linear';       ...
      'ylabel',         'h';          ...
      'yunit',          'km';             ...
      'zlim',           [-400 400];    ...
      'zscale',         'linear';       ...
      'colormap',       cmap{1}};
      
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end
%%
end

