global database datasetinfo drawopt

% NOTE: Add the parameter information whenever a new parameters is added!


databasetemplate=database_variabletemplates(1);

%% OMNI database
parainfo={'Bx_gsm',        ...
          'By_gsm',        ...
          'Bz_gsm',        ...
          'Btot_gsm',       ...
          'v_sw',           ...
          'E_sw',           ...
          'Temp',           ...
          'N_p',            ...
          'Pdyn',           ...
          'AE',             ...
          'AL',             ...
          'AU',             ...
          'PC'};
          
          
ix=ismember(parainfo,datasetinfo.paralist);
if ~isempty(parainfo(ix))
  % linked file for reading FPI data
  filereader_OMNI='assign_OMNI.m';
  
  %% Item 1: Bx GSM
  itemname='Bx_gsm';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'Bx_gsm';        ...
    'label',        'B_x^{GSM}';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'IMF';    ...
    'dscp',         'IMF x component (GSM)';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  
  %% Item 2: By GSM
  itemname='By_gsm';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'By_gsm';        ...
    'label',        'B_y^{GSM}';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'IMF';    ...
    'dscp',         'IMF y component (GSM)';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  
  %% Item 3: Bz GSM
  itemname='Bz_gsm';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'Bz_gsm';        ...
    'label',        'B_z^{GSM}';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'IMF';    ...
    'dscp',         'IMF z component (GSM)';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  %% Item 4: Btot in GSM y-z plane
  itemname='Btot_gsm';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'Btot_gsm';        ...
    'label',        'B_T^{GSM}';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'IMF';    ...
    'dscp',         'IMF Bt in GSM y-z plane';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  %% Item 5: solar wind velocity
  itemname='v_sw';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'v_sw';        ...
    'label',        'v_{SW}';          ...
    'unit',         'km/s';          ...
    'ndim',          1;              ...
    'group',        'OMNI solar wind';    ...
    'dscp',         'Volar wind velocity';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  %% Item 6: solar wind electric field
  itemname='E_sw';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'E_sw';        ...
    'label',        'E_{SW}';          ...
    'unit',         '';          ...
    'ndim',          1;              ...
    'group',        'OMNI solar wind';    ...
    'dscp',         'Solar wind electric field';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  %% Item 7: solar wind temperature
  itemname='Temp';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'Temp';        ...
    'label',        'T_p';          ...
    'unit',         'K';          ...
    'ndim',          1;              ...
    'group',        'OMNI solar wind';    ...
    'dscp',         'Solar wind temperature';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  %% Item 8: proton density
  itemname='N_p';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'N_p';        ...
    'label',        'log_10(n_p)';          ...
    'unit',         '';          ...
    'ndim',          1;              ...
    'group',        'OMNI solar wind';    ...
    'dscp',         'Solar wind proton density';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  %% Item 9: dynamic pressure
  itemname='Pdyn';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'Pdyn';        ...
    'label',        'log_10(P_{dyn})';          ...
    'unit',         '';          ...
    'ndim',          1;              ...
    'group',        'OMNI solar wind';    ...
    'dscp',         'Solar wind dynamic pressure';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  %% Item 10: AE index
  itemname='AE';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'AE';        ...
    'label',        'AE';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'Indices';    ...
    'dscp',         'Solar wind proton density';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  %% Item 11: AL index
  itemname='AL';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'AL';        ...
    'label',        'AL';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'Indices';    ...
    'dscp',         'Solar wind proton density';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  %% Item 12: AU index
  itemname='AU';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'AU';        ...
    'label',        'AU';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'Indices';    ...
    'dscp',         'Solar wind proton density';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
  
  %% Item 13: PC index
  itemname='PC';
  database.(itemname)=databasetemplate;
  item={                            ...
    'name',         'PC';        ...
    'label',        'PC';          ...
    'unit',         'mV/m';          ...
    'ndim',          1;              ...
    'group',        'Geomagnetic indices';    ...
    'dscp',         'Solar wind proton density';      ...
    'filereader',   filereader_OMNI  ...
    };
  for i=1:size(item,1)
    database.(itemname).(item{i,1})=item{i,2};
  end
%% plot settings
  vis_init_OMNI;
end