%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%% database for IL, IU, IE index from FMI/IMAGE    %%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

global database datasetinfo drawopt

% NOTE: Add the parameter information whenever a new parameters is added!


databasetemplate=database_variabletemplates(1);

parainfo={'IL',  ...
          'IU',  ...
          'IE'};
ix=ismember(parainfo,datasetinfo.paralist);
if ~isempty(parainfo(ix))
  % linked file for reading FPI data
  filereader='assign_IMAGEMAG_IL.m';
  %% Item 1: IL Index
  database.IL=databasetemplate;
  item={                            ...
    'name',         'IL';        ...
    'label',        'IL';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'IMAGE indices';    ...
    'dscp',         'FMI IMAGE indices';      ...
    'filereader',   filereader};
  for i=1:size(item,1)
    database.IL.(item{i,1})=item{i,2};
  end
  %% Item 2: IU Index
  database.IU=databasetemplate;
  item={                            ...
    'name',         'IU';        ...
    'label',        'IU';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'IMAGE indices';    ...
    'dscp',         'FMI IMAGE indices';      ...
    'filereader',   filereader};
  for i=1:size(item,1)
    database.IU.(item{i,1})=item{i,2};
  end 
  %% Item 3: IE Index
  database.IE=databasetemplate;
  item={                            ...
    'name',         'IE';        ...
    'label',        'IE';          ...
    'unit',         'nT';          ...
    'ndim',          1;              ...
    'group',        'IMAGE indices';    ...
    'dscp',         'FMI IMAGE indices';      ...
    'filereader',   filereader};
  for i=1:size(item,1)
    database.IE.(item{i,1})=item{i,2};
  end 
  
  %% Initialize plot settings
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  vis_init_IMAGEMAG_IL;
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end