global database

drawopttemplate=vis_drawopttemplates(1);

% NOTE: Add the parameter information whenever a new parameters is added!

%% OMNI database
parainfo={'Bx_gsm',        ...
          'By_gsm',        ...
          'Bz_gsm',        ...
          'Btot_gsm',       ...
          'v_sw',           ...
          'E_sw',           ...
          'Temp',           ...
          'N_p',            ...
          'Pdyn',           ...
          'AE',             ...
          'AL',             ...
          'AU',             ...
          'PC'};
        
%% Item 1: Bx GSM
itemname='Bx_gsm';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 2: By GSM
itemname='By_gsm';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 3: Bz GSM
itemname='Bz_gsm';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 4: Btot GSM
itemname='Btot_gsm';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [0 inf];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 5: solar wind velocity
itemname='v_sw';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 6: solar wind electric field
itemname='E_sw';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 7: solar wind temperature
itemname='Temp';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 8: solar wind density
itemname='N_p';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 9: solar wind dynamic pressure
itemname='Pdyn';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 10: AE index
itemname='AE';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 11: AL index
itemname='AL';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end
%% Item 12: AU index
itemname='AU';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 13: PC index
itemname='PC';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end
