global database

drawopttemplate=vis_drawopttemplates(1);

% NOTE: Add the parameter information whenever a new parameters is added!

parainfo={'u55_N',  ...
          'u55_E',  ...
          'u55_h',  ...
          'u55_bm1',    ...
          'u55_bm2',    ...
          'u55_bm3',    ...
          'u55_bm4',    ...
          'u55_bm5',    ...
          'a55_N',      ...
          'a55_E'};
        
%% Item 1: u55_N
database.u55_N.drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-300 100];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.u55_N.drawopt.(item{i,1})=item{i,2};
end

%% Item 2: u55_E
database.u55_E.drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-420 20];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.u55_E.drawopt.(item{i,1})=item{i,2};
end

%% Item 3: u55_h
database.u55_h.drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.u55_h.drawopt.(item{i,1})=item{i,2};
end

%% Item 4: u55_bm1
itemname='u55_bm1';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 5: u55_bm2
itemname='u55_bm2';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 6: u55_bm3
itemname='u55_bm3';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 7: u55_bm4
itemname='u55_bm4';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 8: u55_bm5
itemname='u55_bm5';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 9: a55_N
itemname='a55_N';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 10: a55_E
itemname='a55_E';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-0.45 0.25];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end