global database

drawopttemplate=vis_drawopttemplates(1);

% NOTE: Add the parameter information whenever a new parameters is added!

parainfo={'u63_N',  ...
          'u63_E',  ...
          'u63_h',  ...
          'u63_bm1',    ...
          'u63_bm2',    ...
          'u63_bm3',    ...
          'u63_bm4',    ...
          'u63_bm5',    ...
          'a63_N',      ...
          'a63_E'};
        
%% Item 1: u63_N
database.u63_N.drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-300 100];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.u63_N.drawopt.(item{i,1})=item{i,2};
end

%% Item 2: u63_E
database.u63_E.drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-420 20];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.u63_E.drawopt.(item{i,1})=item{i,2};
end

%% Item 3: u63_h
database.u63_h.drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.u63_h.drawopt.(item{i,1})=item{i,2};
end

%% Item 4: u63_bm1
itemname='u63_bm1';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 5: u63_bm2
itemname='u63_bm2';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 6: u63_bm3
itemname='u63_bm3';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 7: u63_bm4
itemname='u63_bm4';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...u63_bm2
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 8: u63_bm5
itemname='u63_bm5';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 9: a63_N
itemname='a63_N';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end

%% Item 10: a63_E
itemname='a63_E';
database.(itemname).drawopt=drawopttemplate;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-0.45 0.25];       ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.(itemname).drawopt.(item{i,1})=item{i,2};
end