global database datasetinfo

drawopttemplate1=vis_drawopttemplates(1);
drawopttemplate2=vis_drawopttemplates(2);
% NOTE: Add the parameter information whenever a new parameters is added!

parainfo={'EQ1Eext',  ...
          'EQ1Eext_mono'};
        
cmap=axes_colormaps(0);       
%% Item 1: JEQ east external
database.EQ1Eext.drawopt=drawopttemplate2;
item={                                  ...
      'xdatagrid',      'off';          ...
      'xdatagridres',   [];             ...
      'xlabel',         'UT';       	...
      'ydataname',      'lat';          ...
      'ydatagrid',      'off';          ...
      'ydatagridres',   [];             ...
      'ylim',           [64 75];        ...
      'yscale',         'linear';       ...
      'ylabel',         'lat';          ...
      'yunit',          [];             ...
      'zlim',           [-600 600];    ...
      'zscale',         'linear';       ...
      'colormap',       cmap{1}};
      
for i=1:size(item,1)
  database.EQ1Eext.drawopt.(item{i,1})=item{i,2};
end

%% Item 2: Jeq eat at a single site
database.EQ1Eext_mono.drawopt=drawopttemplate1;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.EQ1Eext_mono.drawopt.(item{i,1})=item{i,2};
end

%% Item 3: Jeq northward external
database.EQ1Next.drawopt=drawopttemplate2;
item={                                  ...
      'xdatagrid',      'off';          ...
      'xdatagridres',   [];             ...
      'xlabel',         'UT';       	...
      'ydataname',      'lat';          ...
      'ydatagrid',      'off';          ...
      'ydatagridres',   [];             ...
      'ylim',           [64 75];        ...
      'yscale',         'linear';       ...
      'ylabel',         'lat';          ...
      'yunit',          [];             ...
      'zlim',           [-600 600];    ...
      'zscale',         'linear';       ...
      'colormap',       cmap{1}};
      
for i=1:size(item,1)
  database.EQ1Next.drawopt.(item{i,1})=item{i,2};
end

%% Item 4: Jeq northward at a single site
database.EQ1Next_mono.drawopt=drawopttemplate1;
item={                                  ...
      'xlabel',         'UT';       	...
      'ylim',           [-inf inf];     ...
      'yscale',         'linear'};
for i=1:size(item,1)
  database.EQ1Next_mono.drawopt.(item{i,1})=item{i,2};
end
%%