function template=vis_drawopttemplates(ind)
  drawopttemplist{1}=struct(                            ...
          'xdataname',       [],                      ...
          'xdatagrid',       '',                      ...
          'xdatares',        [],                      ...
          'xdatascatter',    '',                      ...
          'xlabel',          '',                      ...
          'xunit',           '',                      ...
          'xlim',            [],                      ...
          'ydataname',       [],                      ...
          'ylabel',          '',                      ...
          'yunit',           '',                      ...
          'ytick',           [],                      ...
          'yticklabel',      [],                      ...
          'ylim',            [],                      ...
          'yscale',          ''                       ...           
          );
  drawopttemplist{2}=struct(                            ...
          'xdataname',       [],                      ...
          'xlabel',          '',                      ...
          'xunit',           '',                      ...
          'xlim',            [],                      ...
          'xdatagrid',       '',                      ...
          'xdatares',        [],                      ... 
          'xdatascatter',    '',                      ...
          'ydataname',       [],                      ...
          'ylabel',          '',                      ...
          'yunit',           '',                      ...
          'ytick',           [],                      ...
          'yticklabel',      [],                      ...
          'ylim',            [],                      ...
          'yscale',          '',                      ...
          'ydatagrid',       [],                      ...
          'ydatares',        [],                      ...
          'ydatascatter',    '',                      ...
          'zdataname',       [],                      ...
          'zlabel',          '',                      ...
          'zunit',           '',                      ...
          'ztick',           [],                      ...
          'zticklabel',      [],                      ...
          'zlim',            [],                      ...
          'zscale',          '',                      ...
          'colormap',        []                       ...
          );
  template=drawopttemplist{ind};
end